# Generated by Django 5.0.4 on 2024-04-10 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BeeHive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_number', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('inspected_at', models.DateTimeField(blank=True, null=True)),
                ('hive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='bee_app.beehive')),
            ],
            options={
                'unique_together': {('hive', 'slide_number')},
            },
        ),
        migrations.CreateModel(
            name='Bee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('queen', 'Queen'), ('worker', 'Worker'), ('guard', 'Guard'), ('larva', 'Larva'), ('mite', 'Mite')], max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bees', to='bee_app.slide')),
            ],
        ),
    ]
