# Generated by Django 5.0.4 on 2024-04-12 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='zip_code',
            field=models.CharField(default=60605, max_length=10),
            preserve_default=False,
        ),
    ]
